/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['default']
    NutDatePicker: typeof import('nutui-uniapp/components/datepicker/datepicker.vue')['default']
    NutDialog: typeof import('nutui-uniapp/components/dialog/dialog.vue')['default']
    NutMenu: typeof import('nutui-uniapp/components/menu/menu.vue')['default']
    NutMenuItem: typeof import('nutui-uniapp/components/menuitem/menuitem.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
    NutUploader: typeof import('nutui-uniapp/components/uploader/uploader.vue')['default']
  }
}
